### ISSUE TITLE
String Not Contains Filter

### ISSUE THREAD

**Issue by mehmetuken** [enisn/AutoFilterer#46]

**Comment by enisn** [comment]
As I understand, you're talking about something like below:
```csharp
    [StringFilterOptions(StringFilterOption.NotContains)]
    public string Name { get; set; }
```

StringFilter calls a method, and each enum member presents a string method. But there is no method named 'NotContains', you implementing it requires architectural changes.


Instead of this custom development, I'll consider adding negativity to queries. like adding an exclamation mark at the beginning of the LINQ query.

x => x.Name.Contains(something)
x => !x.Name.Contains(something)
